# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rango', '0004_auto_20161009_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Views',
                                    to='rango.Category'),
        ),
    ]
