# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rango', '0005_auto_20161009_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
